import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Archive, Boxes, Plus, Shapes } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ComponentTypes() {
  const { user } = useAuth(); const utils = trpc.useUtils();
  const { data: types, isLoading } = trpc.organization.componentTypes.list.useQuery(undefined, { enabled: user?.role === "admin" });
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [search, setSearch] = useState("");
  const filteredTypes = (types ?? []).filter(type => `${type.name} ${type.description ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const create = trpc.organization.componentTypes.create.useMutation({ onSuccess: async () => { toast.success("Component type added."); setName(""); setDescription(""); await utils.organization.componentTypes.list.invalidate(); }, onError: error => toast.error(error.message) });
  const archive = trpc.organization.componentTypes.archive.useMutation({ onSuccess: async () => { toast.success("Component type archived."); await utils.organization.componentTypes.list.invalidate(); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin") return <div className="panel p-12 text-center"><Shapes className="mx-auto h-6 w-6 text-[#0178D4]" /><h1 className="mt-4 text-xl font-bold text-[#0B2E4E]">Admin access required</h1><p className="mt-2 text-sm text-slate-500">Only Admin users can manage general component types.</p></div>;
  return <div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><section className="panel p-6"><p className="eyebrow">General component taxonomy</p><h1 className="mt-1 text-xl font-bold text-[#0B2E4E]">Add component type</h1><p className="mt-2 text-sm leading-6 text-slate-500">Create types for 3D Printing, Fasteners, Adhesives, Soap, Company Supplies, or any category that does not belong to an engineering department.</p><form onSubmit={event => { event.preventDefault(); create.mutate({ name: name.trim(), description: description.trim() || undefined }); }} className="mt-6 space-y-4"><div className="space-y-2"><Label htmlFor="type-name">Type name</Label><Input id="type-name" value={name} onChange={event => setName(event.target.value)} placeholder="e.g. 3D Printing" required /></div><div className="space-y-2"><Label htmlFor="type-description">Description</Label><Textarea id="type-description" value={description} onChange={event => setDescription(event.target.value)} placeholder="Optional scope or storage guidance" rows={4} /></div><Button type="submit" disabled={create.isPending} className="bg-[#0178D4] hover:bg-[#0065B3] text-white gap-2"><Plus className="h-4 w-4" />Add type</Button></form></section><section className="panel overflow-hidden"><div className="px-6 py-5 border-b border-[#E8EEF3]"><p className="eyebrow">Searchable classification</p><h2 className="mt-1 text-lg font-bold text-[#0B2E4E]">Component types</h2><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search type or description…" className="mt-4 bg-white" /></div><div className="divide-y divide-[#E8EEF3]">{isLoading && <div className="p-6 text-sm text-slate-500">Loading types…</div>}{!isLoading && filteredTypes.map(type => <div key={type.id} className="p-5 flex items-center gap-4"><div className={`h-10 w-10 rounded-xl grid place-items-center ${type.isActive ? "bg-[#E7F8F4] text-[#00A58D]" : "bg-slate-100 text-slate-400"}`}><Boxes className="h-4 w-4" /></div><div className="flex-1"><p className="font-semibold text-[#0B2E4E]">{type.name}</p><p className="mt-1 text-xs text-slate-500">{type.description || "No description"}</p></div>{type.isActive ? <Button size="sm" variant="outline" onClick={() => archive.mutate({ id: type.id })} className="text-rose-700 border-rose-200 gap-1"><Archive className="h-3.5 w-3.5" />Archive</Button> : <Badge variant="outline" className="text-slate-500">Archived</Badge>}</div>)}{!isLoading && !filteredTypes.length && <div className="p-12 text-center text-sm text-slate-500">No component types match this search.</div>}</div></section></div>;
}
