import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Archive, Boxes, Plus, Search, Shapes } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ComponentTypes() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const { data: types, isLoading } = trpc.organization.componentTypes.list.useQuery(undefined, { enabled: user?.role === "admin" }); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [search, setSearch] = useState("");
  const filteredTypes = (types ?? []).filter(type => `${type.name} ${type.description ?? ""}`.toLowerCase().includes(search.toLowerCase()));
  const create = trpc.organization.componentTypes.create.useMutation({ onSuccess: async () => { toast.success("تمت إضافة نوع المكون."); setName(""); setDescription(""); await utils.organization.componentTypes.list.invalidate(); }, onError: error => toast.error(error.message) });
  const archive = trpc.organization.componentTypes.archive.useMutation({ onSuccess: async () => { toast.success("تمت أرشفة نوع المكون."); await utils.organization.componentTypes.list.invalidate(); }, onError: error => toast.error(error.message) });
  if (user?.role !== "admin") return <div className="panel p-12 text-center"><Shapes className="mx-auto h-6 w-6 text-[#0178D4]" /><h1 className="mt-4 text-xl font-bold text-[#0B2E4E]">صلاحية أدمن مطلوبة</h1><p className="mt-2 text-sm text-slate-500">إدارة أنواع المكونات العامة متاحة لمستخدمي الأدمن فقط.</p></div>;
  return <div className="grid gap-6 xl:grid-cols-[.7fr_1.3fr]"><section className="panel p-6"><p className="eyebrow">تصنيف المكونات العامة</p><h1 className="mt-1 text-xl font-bold text-[#0B2E4E]">إضافة نوع مكون</h1><p className="mt-2 text-sm leading-6 text-slate-500">أنشئ أنواعًا للطباعة ثلاثية الأبعاد والمسامير واللاصق والصابون ومستلزمات الشركة، أو أي فئة لا ترتبط بقسم هندسي محدد.</p><form onSubmit={event => { event.preventDefault(); create.mutate({ name: name.trim(), description: description.trim() || undefined }); }} className="mt-6 space-y-4"><div className="space-y-2"><Label htmlFor="type-name">اسم النوع</Label><Input id="type-name" value={name} onChange={event => setName(event.target.value)} placeholder="مثال: طباعة ثلاثية الأبعاد" required /></div><div className="space-y-2"><Label htmlFor="type-description">الوصف</Label><Textarea id="type-description" value={description} onChange={event => setDescription(event.target.value)} placeholder="نطاق الاستخدام أو إرشادات التخزين (اختياري)" rows={4} /></div><Button type="submit" disabled={create.isPending} className="gap-2 bg-[#0178D4] text-white hover:bg-[#0065B3]"><Plus className="h-4 w-4" />إضافة النوع</Button></form></section><section className="panel overflow-hidden"><div className="border-b border-[#E8EEF3] px-6 py-5"><p className="eyebrow">تصنيف قابل للبحث</p><h2 className="mt-1 text-lg font-bold text-[#0B2E4E]">أنواع المكونات</h2><div className="relative mt-4"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث باسم النوع أو وصفه…" className="bg-white pr-9" /></div></div><div className="divide-y divide-[#E8EEF3]">{isLoading && <div className="p-6 text-sm text-slate-500">يجري تحميل الأنواع…</div>}{!isLoading && filteredTypes.map(type => <div key={type.id} className="flex items-center gap-4 p-5"><div className={`grid h-10 w-10 place-items-center rounded-xl ${type.isActive ? "bg-[#E7F8F4] text-[#00A58D]" : "bg-slate-100 text-slate-400"}`}><Boxes className="h-4 w-4" /></div><div className="flex-1"><p className="font-semibold text-[#0B2E4E]">{type.name}</p><p className="mt-1 text-xs text-slate-500">{type.description || "لا يوجد وصف"}</p></div>{type.isActive ? <Button size="sm" variant="outline" onClick={() => archive.mutate({ id: type.id })} className="gap-1 border-rose-200 text-rose-700"><Archive className="h-3.5 w-3.5" />أرشفة</Button> : <Badge variant="outline" className="text-slate-500">مؤرشف</Badge>}</div>)}{!isLoading && !filteredTypes.length && <div className="p-12 text-center text-sm text-slate-500">لا توجد أنواع مكونات مطابقة للبحث.</div>}</div></section></div>;
}
