import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/_core/hooks/useAuth";
import { formatDate } from "@/lib/warehouse";
import { exportReportExcel, exportReportPdf } from "@/lib/reportExport";
import { trpc } from "@/lib/trpc";
import { CircleCheck, FileSpreadsheet, FileText, LockKeyhole, Printer, Search } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Invoices() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin";
  const { data: invoices, isLoading } = trpc.warehouse.invoices.list.useQuery(undefined, { enabled: isAdmin });
  const [selectedId, setSelectedId] = useState<number | null>(null); const [search, setSearch] = useState("");
  if (!isAdmin) return <div className="panel mx-auto max-w-2xl p-12 text-center"><LockKeyhole className="mx-auto h-6 w-6 text-[#0178D4]" /><h1 className="mt-4 text-xl font-bold text-[#0B2E4E]">صلاحية أدمن مطلوبة</h1><p className="mt-2 text-sm text-slate-500">سجل فواتير التسليم متاح لمستخدمي الأدمن فقط.</p></div>;
  const filteredInvoices = (invoices ?? []).filter(({ invoice, receiver }) => `${invoice.invoiceNumber} ${invoice.partNameSnapshot} ${invoice.partNumberSnapshot} ${invoice.purposeSnapshot} ${receiver.name ?? ""} ${receiver.email ?? ""}`.toLowerCase().includes(search.toLowerCase())); const selected = filteredInvoices.find(entry => entry.invoice.id === selectedId) || filteredInvoices[0];
  const exportInvoices = async (format: "excel" | "pdf") => { const rows = filteredInvoices.map(({ invoice, receiver }) => ({ number: invoice.invoiceNumber, section: invoice.warehouseSectionSnapshot === "products" ? "المنتجات" : "المكونات", code: invoice.partNumberSnapshot, item: invoice.partNameSnapshot, quantity: invoice.quantity, receiver: receiver.name || receiver.email || "—", purpose: invoice.purposeSnapshot, receipt: invoice.receiptConfirmedAt ? `مؤكد باسم ${invoice.receiptConfirmationName}` : "بانتظار التأكيد", issuedAt: formatDate(invoice.issuedAt) })); const columns = [{ label: "رقم الفاتورة", value: (row: typeof rows[number]) => row.number }, { label: "القسم", value: (row: typeof rows[number]) => row.section }, { label: "كود القطعة", value: (row: typeof rows[number]) => row.code }, { label: "العنصر", value: (row: typeof rows[number]) => row.item }, { label: "الكمية", value: (row: typeof rows[number]) => row.quantity }, { label: "المستلم", value: (row: typeof rows[number]) => row.receiver }, { label: "الغرض", value: (row: typeof rows[number]) => row.purpose }, { label: "تأكيد الاستلام", value: (row: typeof rows[number]) => row.receipt }, { label: "تاريخ الإصدار", value: (row: typeof rows[number]) => row.issuedAt }]; try { if (format === "excel") await exportReportExcel("سجل فواتير التسليم", "reverse-tech-handover-invoices", columns, rows); else await exportReportPdf("سجل فواتير التسليم", "reverse-tech-handover-invoices", columns, rows); toast.success(`تم تصدير سجل الفواتير بصيغة ${format === "excel" ? "Excel" : "PDF"}.`); } catch { toast.error("تعذر إنشاء ملف التصدير. يُرجى المحاولة مرة أخرى."); } };
  return <div className="space-y-6"><section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">توثيق التسليم اليدوي</p><h1 className="page-title">فواتير التسليم</h1><p className="page-subtitle">ينشئ كل تسليم مكتمل فاتورة تشمل تأكيد المستلم الرقمي عند إتمامه.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => exportInvoices("excel")} className="gap-2"><FileSpreadsheet className="h-4 w-4 text-[#0178D4]" />Excel</Button><Button variant="outline" onClick={() => exportInvoices("pdf")} className="gap-2"><FileText className="h-4 w-4 text-[#0178D4]" />PDF</Button></div></section><div className="grid gap-6 xl:grid-cols-[.95fr_1.05fr]"><section className="panel overflow-hidden"><div className="border-b border-[#E8EEF3] px-6 py-5"><p className="eyebrow">سجل قابل للبحث</p><h2 className="mt-1 font-bold text-[#0B2E4E]">سجل الفواتير</h2><div className="relative mt-4"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="ابحث برقم الفاتورة أو القطعة أو المستلم أو الغرض…" className="bg-white pr-9" /></div></div><div className="divide-y divide-[#E8EEF3]">{isLoading && <div className="p-6 text-sm text-slate-500">يجري تحميل الفواتير…</div>}{!isLoading && filteredInvoices.map(({ invoice, receiver }) => <button key={invoice.id} onClick={() => setSelectedId(invoice.id)} className={`w-full p-5 text-right transition-colors ${selected?.invoice.id === invoice.id ? "bg-[#F1F8FE]" : "hover:bg-[#F7FBFF]"}`}><div className="flex items-center justify-between gap-2"><p className="font-mono text-xs font-bold text-[#0178D4]">{invoice.invoiceNumber}</p><Badge variant="outline" className={invoice.receiptConfirmedAt ? "border-emerald-200 bg-emerald-50 text-emerald-700" : "border-amber-200 bg-amber-50 text-amber-700"}>{invoice.receiptConfirmedAt ? "استلام مؤكد" : "بانتظار التأكيد"}</Badge></div><p className="mt-2 font-semibold text-[#0B2E4E]">{invoice.partNameSnapshot} × {invoice.quantity}</p><p className="mt-1 text-xs text-slate-500">استلمه {receiver.name || receiver.email} · {formatDate(invoice.issuedAt)}</p></button>)}{!isLoading && !filteredInvoices.length && <div className="p-12 text-center"><FileText className="mx-auto h-6 w-6 text-slate-400" /><p className="mt-3 text-sm text-slate-500">لا توجد فواتير مطابقة للبحث.</p></div>}</div></section><section className="panel p-7 print:border-0 print:shadow-none">{selected ? <InvoicePreview selected={selected} /> : <div className="grid h-full min-h-80 place-items-center text-center"><div><FileText className="mx-auto h-7 w-7 text-slate-400" /><p className="mt-3 text-sm text-slate-500">اختر فاتورة لمراجعتها وطباعتها.</p></div></div>}</section></div></div>;
}

function InvoicePreview({ selected }: { selected: any }) { const { invoice, receiver } = selected; return <><div className="flex items-start justify-between gap-4 border-b border-[#E8EEF3] pb-5"><div><div className="inline-flex rounded-md border border-[#E8EEF3] bg-white p-2"><img src="/manus-storage/reverse-tech-logo_04d48f19.webp" alt="REVERSE TECH" className="h-7 w-auto" /></div><p className="mt-4 text-[10px] font-bold tracking-[.12em] text-[#0178D4]">فاتورة تسليم من المخزن</p><h2 className="mt-1 font-mono text-2xl font-extrabold text-[#0B2E4E]">{invoice.invoiceNumber}</h2></div><Button onClick={() => window.print()} className="gap-2 bg-[#0178D4] text-white hover:bg-[#0065B3] print:hidden"><Printer className="h-4 w-4" />طباعة</Button></div><dl className="mt-6 grid grid-cols-2 gap-5 text-sm"><Data label="تاريخ ووقت الإصدار" value={formatDate(invoice.issuedAt)} /><Data label="المستخدم المستلم" value={receiver.name || receiver.email} /><Data label="قسم المخزن" value={invoice.warehouseSectionSnapshot === "products" ? "المنتجات" : "المكونات"} /><Data label="الكمية المسلّمة" value={`${invoice.quantity} وحدة`} /></dl><div className="mt-7 rounded-xl border border-[#DCEAF7] bg-[#F7FBFF] p-5"><p className="font-mono text-xs text-slate-500">{invoice.partNumberSnapshot}</p><p className="mt-2 text-lg font-bold text-[#0B2E4E]">{invoice.partNameSnapshot}</p><p className="mt-3 text-sm leading-6 text-slate-600"><span className="font-semibold text-[#0B2E4E]">الغرض:</span> {invoice.purposeSnapshot}</p></div><div className={`mt-5 rounded-xl border p-4 ${invoice.receiptConfirmedAt ? "border-emerald-200 bg-emerald-50" : "border-amber-200 bg-amber-50"}`}>{invoice.receiptConfirmedAt ? <div className="flex gap-3"><CircleCheck className="mt-0.5 h-5 w-5 text-emerald-600" /><div><p className="font-semibold text-emerald-900">تم تأكيد الاستلام رقميًا</p><p className="mt-1 text-sm text-emerald-800">{invoice.receiptConfirmationName} · {formatDate(invoice.receiptConfirmedAt)}</p>{invoice.receiptNote && <p className="mt-2 text-sm text-emerald-800">ملاحظة المستلم: {invoice.receiptNote}</p>}</div></div> : <p className="text-sm text-amber-800">بانتظار المستلم لتأكيد استلامه رقميًا من صفحة «طلباتي».</p>}</div><div className="mt-12 grid grid-cols-2 gap-8 text-sm"><div className="border-t border-slate-300 pt-2 text-slate-500">أصدرها أدمن المخزن</div><div className="border-t border-slate-300 pt-2 text-slate-500">استلمها {receiver.name || "المستخدم الطالب"}</div></div></>; }
function Data({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs text-slate-400">{label}</dt><dd className="mt-1 font-semibold text-[#0B2E4E]">{value}</dd></div>; }
