import { Badge } from "@/components/ui/badge";
import { useAuth } from "@/_core/hooks/useAuth";
import { formatDate } from "@/lib/warehouse";
import { trpc } from "@/lib/trpc";
import { ArrowDownRight, ArrowRight, ArrowUpRight, History, LockKeyhole } from "lucide-react";

const eventLabels: Record<string, string> = {
  part_created: "Part created", part_updated: "Inventory updated", request_submitted: "Request submitted", request_approved: "Request approved", request_rejected: "Request rejected", delivery_confirmed: "Handover confirmed",
};

export default function Transactions() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const { data: transactions, isLoading } = trpc.warehouse.transactions.useQuery(undefined, { enabled: isAdmin });
  if (!isAdmin) return <div className="panel p-12 text-center max-w-2xl mx-auto"><div className="h-12 w-12 grid place-items-center rounded-xl bg-slate-100 mx-auto"><LockKeyhole className="h-5 w-5 text-slate-500" /></div><h1 className="mt-5 text-xl font-semibold text-slate-950">Admin access required</h1><p className="mt-2 text-sm text-slate-500">The immutable warehouse audit trail is available to the warehouse manager only.</p></div>;
  return <div className="space-y-6"><section><p className="eyebrow">Audit history</p><h1 className="page-title">Transaction ledger</h1><p className="page-subtitle">A permanent record of inventory updates, requests, decisions, and confirmed engineering handovers.</p></section><section className="panel overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left"><thead className="bg-slate-50 border-b border-slate-100"><tr className="text-[11px] uppercase tracking-[0.12em] text-slate-500"><th className="px-6 py-4">Date</th><th className="px-4 py-4">Movement</th><th className="px-4 py-4">Part details</th><th className="px-4 py-4">Engineer</th><th className="px-4 py-4">Stock movement</th><th className="px-6 py-4">Audit note</th></tr></thead><tbody className="divide-y divide-slate-100">{isLoading && Array.from({ length: 6 }).map((_, index) => <tr key={index}><td className="p-5" colSpan={6}><div className="h-6 rounded bg-slate-100 animate-pulse" /></td></tr>)}{!isLoading && transactions?.map(({ transaction, engineer }) => { const isOutgoing = transaction.quantityDelta < 0; const isIncoming = transaction.quantityDelta > 0; return <tr key={transaction.id} className="hover:bg-slate-50/70"><td className="px-6 py-4 text-sm text-slate-600 whitespace-nowrap">{formatDate(transaction.createdAt)}</td><td className="px-4 py-4"><Badge variant="outline" className="bg-slate-50 border-slate-200 text-slate-700">{eventLabels[transaction.type]}</Badge></td><td className="px-4 py-4"><p className="font-medium text-slate-900">{transaction.partNameSnapshot}</p><p className="font-mono text-xs text-slate-500 mt-1">{transaction.partNumberSnapshot}</p></td><td className="px-4 py-4 text-sm text-slate-700">{engineer?.name || engineer?.email || "—"}</td><td className="px-4 py-4">{isOutgoing ? <span className="inline-flex items-center gap-1.5 font-semibold text-rose-700"><ArrowDownRight className="h-4 w-4" />{transaction.quantityDelta}</span> : isIncoming ? <span className="inline-flex items-center gap-1.5 font-semibold text-emerald-700"><ArrowUpRight className="h-4 w-4" />+{transaction.quantityDelta}</span> : <span className="inline-flex items-center gap-1.5 text-slate-400"><ArrowRight className="h-4 w-4" />No change</span>}</td><td className="px-6 py-4 max-w-xs text-sm text-slate-500 leading-relaxed">{transaction.details || "—"}</td></tr>;})}</tbody></table></div>{!isLoading && !transactions?.length && <div className="py-16 text-center"><History className="mx-auto h-5 w-5 text-slate-400" /><h2 className="mt-4 font-semibold text-slate-900">No movements recorded</h2><p className="text-sm text-slate-500 mt-1">The ledger will populate automatically as inventory is managed.</p></div>}</section></div>;
}
